### ISSUE TITLE
Замечания по lw1

### ISSUE THREAD

**Issue by Rabbit864** [RAREGUN/php-github#1]
```php
public function sum($arg): CalculatorAlt
```
Нет типов у аргументов функций и вместо использования названия класса используйте ```self```

**Comment by Rabbit864** [comment]
```php
public function __construct(int $dd, int $mm, int $yy)
```
По нормальному назвать переменные конструктора

**Comment by RAREGUN** [comment]
> Нет типов у аргументов функций

Пропустил
